const DEFAULTPATH = '../assets/images/';
export default {
  BACKARROW: require(`${DEFAULTPATH}arrow.png`),
  PLAY: require(`${DEFAULTPATH}ic_play.png`),
  FULLSCREEN: require(`${DEFAULTPATH}fullscreen(1).png`),
  LIKE: require(`${DEFAULTPATH}like(1)_2.png`),
  DISLIKE: require(`${DEFAULTPATH}like(1).png`),
  PROFILEPIC: require(`${DEFAULTPATH}profilePic.png`),
  SHARE: require(`${DEFAULTPATH}noun_Share_3304093.png`),
  FAVORITE: require(`${DEFAULTPATH}noun_Heart_2553737.png`),
  DONATE: require(`${DEFAULTPATH}money.png`),
  EXPAND: require(`${DEFAULTPATH}ic_expand.png`),
  FORWARD: require(`${DEFAULTPATH}Page-1_2.png`),
  BACK: require(`${DEFAULTPATH}Page-1.png`),
  MINIMIZE: require(`${DEFAULTPATH}minimize.png`),
  PAUSE: require(`${DEFAULTPATH}pause.png`),
  DOT: require(`${DEFAULTPATH}dot.png`),
  LOADER: require('../assets/lottie/loader.json'),
  MENU: require(`${DEFAULTPATH}dots.png`),
};
